### ISSUE TITLE
Fold Change App doesn't work

### ISSUE THREAD

**Issue by Savi235** [tercen/foldchange_app#2]
Request by Savi. What we requested is to do LFC for Log2 values. Still the ratio is on Log values (For Log values, this is T-C). 

Current version doesnt work because: Unclear how to define control group (or treatment groups). Wizard questions are unclear.

**Comment by ginberg** [comment]
hi Savi, sorry I did not understand correctly at first. I have updated the App in PamgeneEvaluators now, so it calculates the ratio. Also I have updated the texts in the app so it should be more clear which values to choose. Could you have a look at it again?

**Comment by ginberg** [comment]
@Savi235 I have updated the app in PamgeneEvaluators, so it subtracts the values instead of calculating the ratio
